steps:
  # ==========================================================
  # 1. Build and push FastAPI Backend container image
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/web:latest'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: 'build-web'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/web:latest'
    id: 'push-web'
    waitFor: ['build-web']

  # ==========================================================
  # 2. Build and push Streamlit UI container image
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/ui:latest'
      - './ui'
      - '-f'
      - './ui/Dockerfile'
    id: 'build-ui'
    waitFor: ['-'] # Start immediately in parallel

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/ui:latest'
    id: 'push-ui'
    waitFor: ['build-ui']

  # ==========================================================
  # 3. Build and push Next.js Frontend container image
  # ==========================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/frontend:latest'
      - './frontend'
      - '-f'
      - './frontend/Dockerfile'
    id: 'build-frontend'
    waitFor: ['-'] # Start immediately in parallel

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/frontend:latest'
    id: 'push-frontend'
    waitFor: ['build-frontend']

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/web:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/ui:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/regudrift-repo/frontend:latest'

substitutions:
  _REGION: 'asia-south1'

options:
  logging: 'CLOUD_LOGGING_ONLY'
