"use client";

import React, { useState } from "react";

interface Blueprint {
  clause_at_risk: string;
  severity_rating: string;
  clarity_score: number;
  technical_remediation_blueprint: string;
  commit_hash?: string;
  author_name?: string;
  commit_timestamp?: string;
  branch_name?: string;
}

interface RemediationProps {
  blueprints?: Blueprint[];
  onExportPdf?: () => void;
  isExportingPdf?: boolean;
}

export default function Remediation({
  blueprints = [],
  onExportPdf,
  isExportingPdf = false,
}: RemediationProps) {
  const [activeTab, setActiveTab] = useState<"terraform" | "python">("terraform");
  const [copied, setCopied] = useState<boolean>(false);

  const fallbackTerraform = `# Auto-generated remediation for RDS Storage Encryption Drift
# Applies AES-256 encryption using dedicated Customer-Managed Keys (CMK)
# Git Commit context: Commit Blamer baseline

resource "aws_kms_key" "telemetry_encryption" {
  description             = "KMS key for financial telemetry DB"
  deletion_window_in_days = 10
  enable_key_rotation     = true
}

resource "aws_rds_cluster" "financial_telemetry" {
  cluster_identifier      = "aurora-telemetry-cluster"
  engine                  = "aurora-postgresql"
  
  + storage_encrypted     = true
  + kms_key_id            = aws_kms_key.telemetry_encryption.arn
}`;

  const fallbackPython = `# Auto-generated telemetry middleware patch for centralized log signing
# Computes HMAC-SHA256 signature for every log aggregate before console write
# Git Commit context: Commit Blamer baseline

import hmac
import hashlib
import os

SECRET_KEY = os.getenv("TELEMETRY_SIGNING_KEY", "secure_secret_hash_key").encode("utf-8")

def sign_log_payload(payload: str) -> str:
    """
    Computes an HMAC-SHA256 signature on the raw log message text.
    """
    signature = hmac.new(SECRET_KEY, payload.encode("utf-8"), hashlib.sha256)
    return f"SIG={signature.hexdigest()} | MSG={payload}"`;

  const getDynamicCode = (lang: "terraform" | "python") => {
    const filtered = blueprints.filter((bp) => {
      const code = bp.technical_remediation_blueprint.toLowerCase();
      const isPython = code.includes("import ") || code.includes("def ") || code.includes("python") || code.includes("sys.") || code.includes("print(");
      const isTerraform = code.includes("resource ") || code.includes("provider ") || code.includes("terraform {") || code.includes("variable ") || code.includes("aws_");
      
      if (lang === "python") {
        return isPython || !isTerraform;
      } else {
        return isTerraform || !isPython;
      }
    });

    if (filtered.length > 0) {
      let result = `# Dynamic Remediation Plan (${lang === "terraform" ? "Terraform IaC" : "Python Script"}) generated by ReguDrift AI\n`;
      filtered.forEach((bp, idx) => {
        result += `\n# Gap ${idx + 1}: ${bp.clause_at_risk}\n# Severity: ${bp.severity_rating} | Clarity: ${bp.clarity_score}/100\n`;
        if (bp.commit_hash) {
          result += `# Git Commit Context: Hash=${bp.commit_hash} | Author=${bp.author_name || "N/A"} | Branch=${bp.branch_name || "N/A"}\n`;
        }
        result += `\n${bp.technical_remediation_blueprint}\n`;
      });
      return result;
    }
    
    return lang === "terraform" ? fallbackTerraform : fallbackPython;
  };

  const activeCode = getDynamicCode(activeTab);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
    }
  };

  return (
    <section className="flex flex-col gap-3 mt-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xs font-mono font-bold tracking-widest text-on-surface-variant uppercase flex items-center gap-2">
          <span className="text-primary text-sm">💻</span>
          Remediation console
        </h2>
      </div>

      {}
      <div className="border border-outline-variant rounded-xl bg-surface/85 backdrop-blur-md flex flex-col overflow-hidden shadow-md">
        
        {}
        <div className="flex flex-wrap items-center bg-[#070B16] border-b border-outline-variant px-3 justify-between">
          <div className="flex items-center">
            <button
              onClick={() => setActiveTab("terraform")}
              className={`px-4 py-3 text-[10px] font-mono tracking-wide uppercase transition-all border-b-2 ${
                activeTab === "terraform"
                  ? "text-primary border-primary bg-surface/30"
                  : "text-slate-400 border-transparent hover:text-slate-200 hover:bg-surface/10"
              }`}
            >
              Terraform IaC
            </button>
            <button
              onClick={() => setActiveTab("python")}
              className={`px-4 py-3 text-[10px] font-mono tracking-wide uppercase transition-all border-b-2 ${
                activeTab === "python"
                  ? "text-primary border-primary bg-surface/30"
                  : "text-slate-400 border-transparent hover:text-slate-200 hover:bg-surface/10"
              }`}
            >
              Python Script
            </button>
          </div>

          <div className="flex items-center gap-2 py-1.5 pr-1">
            {}
            <button
              onClick={onExportPdf}
              disabled={isExportingPdf}
              className="bg-primary/10 border border-primary/45 hover:bg-primary/20 text-primary font-mono text-[9px] px-3.5 py-1.5 rounded-full transition-all flex items-center gap-1.5 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span>📥</span>
              <span>{isExportingPdf ? "Building PDF..." : "Export Boardroom PDF"}</span>
            </button>

            {}
            <button
              onClick={handleCopy}
              className="text-slate-300 hover:text-white transition-colors flex items-center gap-1 px-3 py-1.5 rounded-full bg-[#121B2E] border border-outline-variant focus:outline-none"
            >
              <span>📋</span>
              <span className="font-mono text-[9px] uppercase">
                {copied ? "Copied!" : "Copy"}
              </span>
            </button>
          </div>
        </div>

        {}
        <div className="p-4 font-mono overflow-x-auto text-[12px] bg-[#030712]/80 min-h-[180px]">
          <pre className="leading-relaxed">
            <code className="text-slate-300 block select-text">
              {activeCode.split("\n").map((line, idx) => {
                const isComment = line.trim().startsWith("#");
                const isAddition = line.trim().startsWith("+");
                
                let lineClass = "text-on-surface-variant/40";
                if (!isComment) {
                  if (isAddition) lineClass = "text-primary font-semibold";
                  else lineClass = "text-[#E2E8F0]";
                } else {
                  lineClass = "text-secondary/70";
                }

                return (
                  <div key={idx} className={lineClass}>
                    {line}
                  </div>
                );
              })}
            </code>
          </pre>
        </div>

      </div>
    </section>
  );
}
