"use client";

import React, { useState } from "react";

interface Blueprint {
  clause_at_risk: string;
  severity_rating: string;
  clarity_score: number;
  technical_remediation_blueprint: string;
}

interface RemediationProps {
  blueprints?: Blueprint[];
  onExportPdf?: () => void;
  isExportingPdf?: boolean;
}

export default function Remediation({
  blueprints = [],
  onExportPdf,
  isExportingPdf = false,
}: RemediationProps) {
  const [activeTab, setActiveTab] = useState<"terraform" | "python">("terraform");
  const [copied, setCopied] = useState<boolean>(false);

  // Static fallback Terraform code when no audit run is active
  const fallbackTerraform = `# Auto-generated remediation for RDS Storage Encryption Drift
# Applies AES-256 encryption using dedicated Customer-Managed Keys (CMK)

resource "aws_kms_key" "telemetry_encryption" {
  description             = "KMS key for financial telemetry DB"
  deletion_window_in_days = 10
  enable_key_rotation     = true
}

resource "aws_rds_cluster" "financial_telemetry" {
  cluster_identifier      = "aurora-telemetry-cluster"
  engine                  = "aurora-postgresql"
  
  + storage_encrypted     = true
  + kms_key_id            = aws_kms_key.telemetry_encryption.arn
}`;

  // Static fallback Python code
  const fallbackPython = `# Auto-generated telemetry middleware patch for centralized log signing
# Computes HMAC-SHA256 signature for every log aggregate before console write

import hmac
import hashlib
import os

SECRET_KEY = os.getenv("TELEMETRY_SIGNING_KEY", "secure_secret_hash_key").encode("utf-8")

def sign_log_payload(payload: str) -> str:
    """
    Computes an HMAC-SHA256 signature on the raw log message text.
    """
    signature = hmac.new(SECRET_KEY, payload.encode("utf-8"), hashlib.sha256)
    return f"SIG={signature.hexdigest()} | MSG={payload}"
`;

  // Dynamically extract blueprints text if active
  const getDynamicCode = (lang: "terraform" | "python") => {
    if (blueprints && blueprints.length > 0) {
      // Return compiled dynamic blueprints or fallback
      let result = `# Dynamic Remediation Plan generated by ReguDrift AI\n`;
      blueprints.forEach((bp, idx) => {
        result += `\n# Gap ${idx + 1}: ${bp.clause_at_risk}\n# Severity: ${bp.severity_rating} | Clarity: ${bp.clarity_score}/100\n`;
        result += `# Remediation Strategy:\n`;
        // Split remediation text into commented lines
        bp.technical_remediation_blueprint.split("\n").forEach((line) => {
          result += `#   ${line}\n`;
        });
      });
      return result;
    }
    return lang === "terraform" ? fallbackTerraform : fallbackPython;
  };

  const activeCode = getDynamicCode(activeTab);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Fallback
    }
  };

  return (
    <section className="flex flex-col gap-component-gap mt-4">
      <div className="flex items-center justify-between mb-2">
        <h2 className="font-title-sm text-lg font-semibold text-on-surface flex items-center gap-2">
          <span className="text-primary text-sm">🛠️</span>
          Remediation Terminal
        </h2>
      </div>

      <div className="border border-outline-variant rounded bg-black flex flex-col overflow-hidden">
        {/* Terminal Header/Tabs */}
        <div className="flex flex-wrap items-center bg-surface-container-high border-b border-outline-variant px-2 justify-between">
          <div className="flex items-center">
            <button
              onClick={() => setActiveTab("terraform")}
              className={`px-4 py-3 font-label-caps text-[10px] uppercase tracking-wider transition-colors border-b-2 ${
                activeTab === "terraform"
                  ? "text-on-surface border-primary bg-surface-container-low"
                  : "text-on-surface-variant border-transparent hover:text-on-surface hover:bg-surface-container-low"
              }`}
            >
              Infrastructure-as-Code (Terraform)
            </button>
            <button
              onClick={() => setActiveTab("python")}
              className={`px-4 py-3 font-label-caps text-[10px] uppercase tracking-wider transition-colors border-b-2 ${
                activeTab === "python"
                  ? "text-on-surface border-primary bg-surface-container-low"
                  : "text-on-surface-variant border-transparent hover:text-on-surface hover:bg-surface-container-low"
              }`}
            >
              Application Patch Code (Python)
            </button>
          </div>

          <div className="flex items-center gap-component-gap py-2 pr-2">
            {/* Export PDF Report Button */}
            <button
              onClick={onExportPdf}
              disabled={isExportingPdf}
              className="bg-primary-container text-primary border border-primary/50 hover:bg-primary/20 font-label-caps text-[10px] px-3 py-1.5 rounded transition-all flex items-center gap-1.5 shadow-[0_0_10px_rgba(195,198,212,0.1)] focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
              title="Export PDF Report"
            >
              <span>📥</span>
              <span>{isExportingPdf ? "Compiling..." : "Export Boardroom-Ready PDF"}</span>
            </button>

            {/* Copy Button */}
            <button
              onClick={handleCopy}
              className="text-on-surface-variant hover:text-primary transition-colors flex items-center gap-1 px-2 py-1.5 rounded bg-surface-container border border-outline-variant focus:outline-none"
              title="Copy Code"
            >
              <span>📋</span>
              <span className="font-label-caps text-[9px] uppercase tracking-wider">
                {copied ? "Copied!" : "Copy"}
              </span>
            </button>
          </div>
        </div>

        {/* Terminal Code Display Area */}
        <div className="p-density-medium font-code-terminal text-code-terminal overflow-x-auto text-[13px] bg-slate-950 min-h-[180px] border-t border-outline-variant/30">
          <pre className="text-on-surface-variant leading-relaxed font-mono p-4">
            <code>{activeCode}</code>
          </pre>
        </div>
      </div>
    </section>
  );
}
